**Question 4**


Code Implementation Task: Implement code to fill the missing data (impute) in daily_vaccinations column per country with the minimum daily vaccination number of relevant countries.  
Note: If a country does not have any valid vaccination number yet, fill it with “0” (zero).

In [31]:
import numpy as np
import pandas as pd

data = pd.read_csv("country_vaccination_stats.csv")
#By grouping the dataset by the country column, I got the minumum of the daily_vaccinations column's data by country.
country_min = data.groupby("country").agg({"daily_vaccinations": "min"})
#I have set the minimum data of the countries for which no data has been entered as 0.
country_min = country_min["daily_vaccinations"].fillna(0)
#I converted the new dataset into a dictionary structure.
dict_country_min = dict(country_min)

#I filled in the key, value matches and the blank values in the first data set with the minimum vaccination value of the countries.
for key, value in dict_country_min.items():
    data.loc[data['country'] == key, "daily_vaccinations"] = data.loc[data['country'] == key, "daily_vaccinations"].fillna(value)

data

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,6483.0,Sputnik V
1,Argentina,12/30/2020,15656.0,Sputnik V
2,Argentina,12/31/2020,15656.0,Sputnik V
3,Argentina,1/1/2021,11070.0,Sputnik V
4,Argentina,1/2/2021,8776.0,Sputnik V
...,...,...,...,...
1497,Wales,1/20/2021,11105.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1498,Wales,1/21/2021,12318.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1499,Wales,1/22/2021,15148.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1500,Wales,1/23/2021,17371.0,"Oxford/AstraZeneca, Pfizer/BioNTech"
1501,Wales,1/24/2021,17063.0,"Oxford/AstraZeneca, Pfizer/BioNTech"

**Question 5**


Code Implementation Task: Implement code to fill the missing data (impute) in daily_vaccinations column per country with the mean daily vaccination number of relevant countries.  
Note: If a country does not have any valid vaccination number yet, fill it with “0” (zero).

In [30]:
import numpy as np
import pandas as pd

data = pd.read_csv("country_vaccination_stats.csv")
#By grouping the dataset by the country column, I got the average of the daily_vaccinations column's data by country.
country_min = data.groupby("country").agg({"daily_vaccinations": "mean"})
#I have set the average data of the countries for which no data has been entered as 0.
country_min = country_min["daily_vaccinations"].fillna(0)
#I converted the new dataset into a dictionary structure.
dict_country_min = dict(country_min)

#I filled in the key, value matches and the blank values in the first data set with the average vaccination value of the countries.
for key, value in dict_country_min.items():
    data.loc[data['country'] == key, "daily_vaccinations"] = data.loc[data['country'] == key, "daily_vaccinations"].fillna(value)

data

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,11446.703704,Sputnik V
1,Argentina,12/30/2020,15656.000000,Sputnik V
2,Argentina,12/31/2020,15656.000000,Sputnik V
3,Argentina,1/1/2021,11070.000000,Sputnik V
4,Argentina,1/2/2021,8776.000000,Sputnik V
...,...,...,...,...
1497,Wales,1/20/2021,11105.000000,"Oxford/AstraZeneca, Pfizer/BioNTech"
1498,Wales,1/21/2021,12318.000000,"Oxford/AstraZeneca, Pfizer/BioNTech"
1499,Wales,1/22/2021,15148.000000,"Oxford/AstraZeneca, Pfizer/BioNTech"
1500,Wales,1/23/2021,17371.000000,"Oxford/AstraZeneca, Pfizer/BioNTech"
1501,Wales,1/24/2021,17063.000000,"Oxford/AstraZeneca, Pfizer/BioNTech"

**Question 6**

Code Implementation Task: Implement code to list the top-3 countries with highest median daily vaccination numbers by considering missing values imputed version of dataset.

In [5]:
import pandas as pd

data = pd.read_csv("country_vaccination_stats.csv")
#By grouping the dataset by the country column, I got the median of the daily_vaccinations column's data by country
country_median = data.groupby("country").agg({"daily_vaccinations": "median"})
#I have set the median data of the countries for which no data has been entered as 0.
country_median = country_median["daily_vaccinations"].fillna(0)
#I am listing the new data set containing the median vaccination values of the countries from largest to smallest.
sorted_value = country_median.sort_values(ascending = False)
#I am listing the 3 countries with the most vaccinations by resetting the indexes.
sorted_value = sorted_value.reset_index()
most_large_three_value = sorted_value.head(3)
most_large_three_value

         country  daily_vaccinations
0  United States            399093.0
1          China            299107.5
2          India            182551.5

**Question 7**

What is the number of total vaccinations done on 1/6/2021 (MM/DD/YYYY) by considering missing values imputed version of dataset?

In [6]:
import pandas as pd
import datetime as dt

data = pd.read_csv("country_vaccination_stats.csv")
total_vaccinations = data[data["date"] == "1/6/2021"]["daily_vaccinations"].sum()
#Sum of all vaccinations on 1/6/2021
print(total_vaccinations)

1466568.0